pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["3_way_merge_basics.html","3-way Merge Concepts","3-way Merge Concepts A merge session helps you combine separate sets of changes into a new version of the data, accommodating both sets of changes...",""],
["archive_files.html","Archive Files","Archive Files Archives are files that contain other files, such as .zip. Beyond Compare displays them as folders, with a zipper icon, but by defau...",""],
["attributes.html","Attributes","Attributes Actions Attributes On the Actions menu, the Attributes command modifies various operating system attributes of the selected files and f...",""],
["automating_a_script.html","Scheduling a Script","Scheduling a Script You can use Beyond Compare&#39;s script processor to perform certain tasks, such as synchronizing folders, without interaction. Fo...",""],
["backup_options.html","Backup Options","Backup Options Tools Options Backups Beyond Compare can create a backup of your files before overwriting them during a copy or move operation, or ...",""],
["bcompare_ftsearch.html","Beyond Compare","Beyond Compare Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enab...",""],
["calling_bc_from_other_applicat.html","Calling BC from Other Applications","Calling BC from Other Applications As you would expect, Beyond Compare&#39;s setup program creates shortcuts to the main executable file, such as: C:\\...",""],
["commands_reference.html","Commands Reference","Commands Reference This part of the documentation describes the commands available in menus and on the toolbar for each view type. Commands that a...",""],
["command_line_reference.html","Command Line Reference","Command Line Reference Command Line Parameters Notice that each parameter should be enclosed in quotation marks if it might contain a space. Param...",""],
["common_commands.html","Common Commands","Common Commands The main menu changes depending on what kind of view is active. However, the commands listed below are common across different vie...",""],
["content_comparisons.html","Content comparisons","Content Comparisons At various times, Beyond Compare performs a content comparison on a pair of files to determine if they match. Content comparis...",""],
["copy.html","Copy","Copy Actions Copy to [Right/Left/Side] On the Actions menu, the Copy to [Right/Left/Side] commands copy the selected files and folders from one si...",""],
["copy_to_folder.html","Copy to Folder","Copy to Folder Actions Copy to Folder On the Actions menu, the Copy to Folder command copies the selected files and folders to a given folder, opt...",""],
["customizing_commands.html","Customize Commands","Customize Commands Tools Customize Commands From the Tools menu, choose Customize Commands . In this dialog you can control which commands appear ...",""],
["data_compare.html","Data Compare Overview","Data Compare Overview A Data Compare session compares text files containing tabular data, such as .csv (comma separated values) files, in a side-b...",""],
["data_compare_columns.html","Data Compare Column Settings","Data Compare Column Settings Session Session Settings Columns Each line in the display represents a comparison column, and shows: Comparison if ke...",""],
["data_compare_commands.html","Data Compare Commands","Data Compare Commands Following is a description of the Data Compare commands, in addition to the common commands . Most of these commands are ava...",""],
["data_compare_formats.html","Data Compare File Formats","Data Compare File Formats Session Session Settings Format Specify the file format to be used when reading the left and/or right files. The default...",""],
["data_compare_options.html","Data Compare Options","Data Compare Options Tools Options File Views Data The Details resize columns to fit option causes the Row Details area at the bottom of a Data Co...",""],
["data_compare_session_settings.html","Data Compare Settings","Data Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs These settings control which files to...",""],
["data_format_conversion_settings.html","Data Format Conversion Settings","Data Format Conversion Settings Data Format Conversion The Conversion tab defines how files should be loaded and saved. Data Compare sessions can ...",""],
["data_format_general_settings.html","Data Format General Settings","Data Format General Settings Data Format General The Mask is a set of file types to be associated with this file format. The Description can inclu...",""],
["data_format_type_settings.html","Data Format Type Settings","Data Format Type Settings Data Format Type The Type tab defines the syntax of the data file. Delimited text files Select Delimited if the fields a...",""],
["delete.html","Delete","Delete Actions Delete On the Actions menu, the Delete command deletes the selected files and folders from one or both sides of the comparison. If ...",""],
["display_filters.html","Display Filters","Display Filters Display filters limit the view to certain comparison results. For example, you can pick Show Differences to hide all the matching ...",""],
["editing_a_column_definition.html","Editing a Column Definition","Editing a Column Definition The Column Handling dialog allows you to set options for each comparison column. A subset of this dialog is used to se...",""],
["editing_a_data_format.html","Data Format Settings","Data Format Settings Data formats are file formats used by the Data Compare session type. Click the tab containing the settings you want to edit: ...",""],
["editing_a_grammar_item.html","Editing a Grammar Item","Editing a Grammar Item Select an existing Element name from the dropdown list or enter your own new name. To define a simple grammar element: Sele...",""],
["editing_a_picture_format.html","Picture Format Settings","Picture Format Settings Picture formats are file formats used by the Picture Compare session type. Click the tab containing the settings you want ...",""],
["editing_a_text_format.html","Text Format Settings","Text Format Settings Text formats are file formats used by the Text Compare and Text Merge session types. Click the tab containing the settings yo...",""],
["editing_text.html","Editing Text","Editing Text Each pane of the Text Compare view is a full-featured text editor. You can enter and edit text like any other text editor, although a...",""],
["exclude.html","Exclude","Exclude Actions Exclude On the Actions menu, the Exclude command filters out the selected files and folders from the current session. It is a hand...",""],
["exporting_settings.html","Exporting Settings","Exporting Settings Tools Export Settings You can selectively save your program settings, in order to transfer them to another computer, upgrade to...",""],
["file_formats.html","File Formats","File Formats Beyond Compare uses file formats to specify how certain types of files are to be handled. For example, files with a .jpg or .png exte...",""],
["file_masks.html","File Masks","File Masks A file mask is a pattern of characters and wildcards used to match folder and file names. Example: *.* would match any filename. For hi...",""],
["file_view_colors.html","File View Comparison Colors","File View Comparison Colors Tools Options File Views Compare Colors These options allow you to customize the colors used to highlight differences ...",""],
["file_view_display_options.html","File View Display Options","File View Display Options Tools Options File Views Display These options allow you to customize visual aspects of the various types of file views....",""],
["file_view_options.html","File View Options","File View Options Tools Options File Views Thumbnail control for large files Select Compress to fit to compress the thumbnail to the available ver...",""],
["filtering_the_view.html","Filtering the Folder Compare View","Filtering the Folder Compare View There are two overall type of filters you can use to control a Folder Compare&#39;s scope: File filters that include...",""],
["find.html","Find","Find To locate specific text in a file view, select Find from the Search menu. Text to find Enter the text to search for. Match character case Mat...",""],
["folder_compare.html","Folder Compare Overview","Folder Compare Overview A Folder Compare session compares two folder structures side-by-side, in a variation of the familiar Explorer style. The c...",""],
["folder_compare_commands.html","Folder Compare Commands","Folder Compare Commands Following is a description of the Folder Compare commands, in addition to the common commands . Most of these commands are...",""],
["folder_compare_criteria.html","Folder Compare Comparison Settings","Folder Compare Comparison Settings Session Session Settings Comparison These settings control what is considered a difference in a folder session....",""],
["folder_compare_handling.html","Folder Compare Handling","Folder Compare Handling Session Session Settings Handling Folder handling Automatically scan subfolders in background causes folders to be read in...",""],
["folder_compare_misc.html","Folder Compare Miscellaneous Settings","Folder Compare Miscellaneous Settings Session Session Settings Misc In the absence of alignment overrides, a folder session aligns files and subfo...",""],
["folder_compare_name_filters.html","Folder Compare Name Filters","Folder Compare Name Filters Session Session Settings Name Filters You can include or exclude folders and files based on their names by using one o...",""],
["folder_compare_other_filters.html","Folder Compare Other Filters","Folder Compare Other Filters Session Session Settings Other Filters You can exclude files from a folder session based on criteria other than their...",""],
["folder_compare_session_settings.html","Folder Compare Settings","Folder Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs These settings control which folder...",""],
["folder_sync.html","Folder Sync Overview","Folder Sync Overview A Folder Sync session is a specialized folder session that synchronizes folders by copying or deleting files. Once you set up...",""],
["folder_sync_commands.html","Folder Sync Commands","Folder Sync Commands Following is a description of the Folder Sync commands, in addition to the common commands . Most of these commands are avail...",""],
["folder_sync_criteria.html","Folder Sync Comparison Settings","Folder Sync Comparison Settings Session Session Settings Comparison These settings control what is considered a difference in a folder session. Qu...",""],
["folder_sync_handling.html","Folder Sync Handling","Folder Sync Handling Session Session Settings Handling Folder handling Sync empty folders will affect folders without content or whose entire cont...",""],
["folder_sync_misc.html","Folder Sync Miscellaneous Settings","Folder Sync Miscellaneous Settings Session Session Settings Misc In the absence of alignment overrides, a folder session aligns files and subfolde...",""],
["folder_sync_name_filters.html","Folder Sync Name Filters","Folder Sync Name Filters Session Session Settings Name Filters You can include or exclude folders and files based on their names by using one or m...",""],
["folder_sync_ops.html","Folder Sync Synchronize Settings","Folder Sync Synchronize Settings Session Session Settings Sync Actions Presets You can use one of the predefined sync methods described in the ove...",""],
["folder_sync_other_filters.html","Folder Sync Other Filters","Folder Sync Other Filters Session Session Settings Other Filters You can exclude files from a folder session based on criteria other than their na...",""],
["folder_sync_session_settings.html","Folder Sync Settings","Folder Sync Settings Session Session Settings Click the tab containing the settings you want to edit: Specs These settings control which folders t...",""],
["folder_view_colors.html","Folder View Comparison Colors","Folder View Comparison Colors Tools Options Folder Views Compare Colors These options allow you to customize the colors used to highlight differen...",""],
["folder_view_confirmations.html","Folder View Confirmations","Folder View Confirmations Tools Options Folder Views Confirmations Confirmations: By default, Beyond Compare prompts for confirmation before perfo...",""],
["folder_view_display_options.html","Folder View Display Options","Folder View Display Options Tools Options Folder Views Display These options allow you to customize overall colors and fonts used in folder views....",""],
["folder_view_log_options.html","Folder View Log Options","Folder View Log Options Tools Options Folder Views Log Set these options to include or exclude types of messages in the log: Operation summaries L...",""],
["folder_view_options.html","Folder View Options","Folder View Options Tools Options Folder Views Name filter presets Specify the preset name filter choices, available on the folder view&#39;s toolbar....",""],
["ftp_access.html","FTP Access","FTP Access In general, wherever base folders are used in Beyond Compare, you can use a folder on an FTP site instead. Browsing to an FTP folder Be...",""],
["ftp_profile_authentication.html","FTP Authentication Settings","FTP Authentication Settings Tools FTP Profiles Authentication These settings apply globally to all profiles. Anonymous logins: Email address When ...",""],
["ftp_profile_connection.html","FTP Connection Settings","FTP Connection Settings Tools FTP Profiles Connection These settings control how the connection is made to the remote server. Connection: Simultan...",""],
["ftp_profile_general.html","FTP General Settings","FTP General Settings Tools FTP Profiles General These settings control general FTP behavior. Login settings: Protocol Specify FTP or one of the se...",""],
["ftp_profile_listings.html","FTP Listing Settings","FTP Listing Settings Tools FTP Profiles Listings Beyond Compare parses the plain text directory listings sent from the FTP server in order to dete...",""],
["ftp_profile_transfer.html","FTP Transfer Settings","FTP Transfer Settings Tools FTP Profiles Transfer These settings control how files are transferred to and from the FTP server. Transfer settings: ...",""],
["general_options.html","General Options","General Options Tools Options General These options control some of the general features of Beyond Compare. To customize the Home view: Enable Inc...",""],
["glossary.html","Glossary","Glossary Base folder The top-most folder on either side of a folder view. Base folder names appear in the toolbar path edits above each pane of th...",""],
["grammars.html","Grammars","Grammars A file format specification can include a grammar definition, used for syntax highlighting, and to help define which differences are impo...",""],
["hex_compare.html","Hex Compare Overview","Hex Compare Overview A Hex Compare session visually compares the raw content of two files, either in a side-by-side or over-under layout. It displ...",""],
["hex_compare_commands.html","Hex Compare Commands","Hex Compare Commands Following is a description of the Hex Compare commands, in addition to the common commands . Most of these commands are avail...",""],
["hex_compare_session_settings.html","Hex Compare Settings","Hex Compare Settings Session Session Settings Specs These settings control which files to compare. Comparison These settings control how the files...",""],
["home_view.html","Home View","The Home View When you open a new window or tab, Beyond Compare displays the Home view: From the Home view, you can: Start a new comparison sessio...",""],
["how_to_compare_folders.html","How to Compare Folders","How to Compare Folders There are several ways to compare folders and files. If you want a quick look at what has changed between two folders, it m...",""],
["how_to_register.html","How to Register","How to Register Step 1 - Try It You can use the program free for 30 days to see if it suits your needs. If you use it beyond 30 days you are oblig...",""],
["how_to_unlock.html","How to Unlock Beyond Compare","How to Unlock Beyond Compare Help Enter Key Beyond Compare is distributed in evaluation mode, allowing you to see if it suits your needs. Unless y...",""],
["importing_settings.html","Importing Settings","Importing Settings Tools Import Settings You can import settings that were previously exported from BC3 or BC2. To import settings: 1. On the Tool...",""],
["license_agreement.html","License Agreement","License Agreement Help About Beyond Compare License Your use of Beyond Compare is governed by the following Terms and Conditions: Acceptance of Li...",""],
["managing_file_formats.html","File Format Management","File Format Management Tools File Formats From the Tools menu, choose File Formats . Here you can see and manage the entire list of file formats. ...",""],
["managing_ftp_profiles.html","FTP Profile Management","FTP Profile Management Tools FTP Profiles From the Tools menu, choose FTP Profiles. Here you can see and manage the entire list of FTP Profiles. E...",""],
["managing_sessions.html","Managing Sessions","Managing Sessions Beyond Compare automatically saves your most recent sessions so you can come back to them easily. If you want to retain a sessio...",""],
["managing_workspaces.html","Managing Workspaces","Managing Workspaces Session Load Workspace Manage Workspaces A workspace is the collection of all open sessions, including the configuration of wi...",""],
["move.html","Move","Move Actions Move to [Right/Left/Side] On the Actions menu, the Move to [Right/Left/Side] commands move the selected files and folders from one si...",""],
["move_to_folder.html","Move to Folder","Move to Folder Actions Move to Folder On the Actions menu, the Move to Folder command moves the selected files and folders to a given folder, opti...",""],
["moving_bc_to_another_computer.html","Moving BC to Another Computer","Moving BC to Another Computer To copy or move Beyond Compare to a different computer: 1. On the new computer, download and install the latest vers...",""],
["mp3_compare_commands.html","MP3 Compare Commands","MP3 Compare Commands Following is a description of the MP3 Compare commands, in addition to the common commands . Most of these commands are avail...",""],
["mp3_compare_session_settings.html","MP3 Compare Settings","MP3 Compare Settings Session Session Settings Specs These settings control which files to compare. Importance These settings control which differe...",""],
["new_folder.html","New Folder","New Folder Actions New Folder On the Actions menu, the New Folder command lets you create a folder at the current position. If you have a file or ...",""],
["next_difference_options.html","File View Next Difference Options","File View Next Difference Options Tools Options File Views Next Difference Set these options to reflect your preferences concerning how to peruse ...",""],
["open_with_applications.html","\"Open With\" Applications","\"Open With\" Applications Tools Options Open With You can configure external applications to appear in the Open With submenu. Click New to add an a...",""],
["other_view_types.html","Other View Types","Other View Types MP3 Compare An MP3 Compare session compares two MP3 files with differences in tag fields highlighted. See also MP3 Compare Comman...",""],
["picture_compare.html","Picture Compare Overview","Picture Compare Overview A Picture Compare session compares a pair of image files visually, showing the differences between them. Aligning Image C...",""],
["picture_compare_commands.html","Picture Compare Commands","Picture Compare Commands Following is a description of the Picture Compare commands, in addition to the common commands . Most of these commands a...",""],
["picture_compare_options.html","Picture Compare Options","Picture Compare Options Tools Options File Views Picture You can change the colors used in Tolerance mode in Picture Compare sessions. Change the ...",""],
["picture_compare_session_settings.html","Picture Compare Settings","Picture Compare Settings Session Session Settings Specs These settings control which files to compare. Format Specify the file format to be used w...",""],
["picture_format_conversion_settings.html","Picture Format Conversion Settings","Picture Format Conversion Settings Picture Format Conversion The Conversion tab defines how files should be loaded. Select a Conversion method. Wh...",""],
["picture_format_general_settings.html","Picture Format General Settings","Picture Format General Settings Picture Format General The Mask is a set of file types to be associated with this file format. The Description can...",""],
["reconciling_differences.html","Reconciling Differences","Reconciling Differences A Folder Compare session provides Actions, such as Copy, Move, Delete and Synchronize, to help you reconcile differences o...",""],
["registry_compare.html","Registry Compare Overview","Registry Compare Overview A Registry Compare session compares live registries on your computer or other computers on your network, and .reg export...",""],
["registry_compare_commands.html","Registry Compare Commands","Registry Compare Commands Following is a description of the Registry Compare commands, in addition to the common commands . Most of these commands...",""],
["registry_compare_session_settings.html","Registry Compare Settings","Registry Compare Settings Session Session Settings Specs These settings control which files to compare. Importance These settings control which di...",""],
["regular_expressions.html","Regular Expression Reference","Regular Expression Reference Regular Expressions are a powerful way to define patterns for searching and matching. Beyond Compare allows you to us...",""],
["rename.html","Rename","Rename Actions Rename On the Actions menu, the Rename command renames the selected files and folders. In the Action subsection, you can select eit...",""],
["renaming_files.html","Renaming Files","Regular Expression Renames In a Folder Compare session you can rename a group of files or folders all at once using Perl-compatible Regular Expres...",""],
["reporting_problems.html","Reporting Problems","Reporting Problems Help Support If you have found a problem with Beyond Compare, we would like to hear from you! From any top-level window, select...",""],
["reports.html","Reports","Reports Comparison reports allow you to save the information from a comparison to view later without re-running the comparison. These reports can ...",""],
["rules_vs_formats.html","Rules vs File Formats","Rules vs File Formats In Beyond Compare, file formats describe the syntax of specific kinds of files by defining elements. File formats are typica...",""],
["sample_regular_expressions.html","Sample Regular Expressions","Sample Regular Expressions Expression Meaning ^abc Match \"abc\" at beginning of line abc$ Match \"abc\" at end of line ^abc$ Match the line \"abc\" exa...",""],
["sample_scripts.html","Sample Scripts","Sample Scripts The following are some sample scripts to show how Beyond Compare can use scripts. You can either use these scripts as is or model y...",""],
["scripting_reference.html","Scripting Reference","Scripting Reference A script is a simple text file containing a list of commands which can control the program and automatically perform file oper...",""],
["scripts_overview.html","Automating with Scripts","Automating with Scripts Beyond Compare provides a script processing feature which allows you to automate routine tasks. A script is a simple text ...",""],
["script_options.html","Script Options","Script Options Tools Options Scripts Set these options to control how scripts are processed: Enable Beep when finished for an audible cue that a s...",""],
["searching_for_text.html","Searching for Text","Searching for Text To search for text in a Text Compare session, select Find from the Search menu. Type the text or a regular expression pattern i...",""],
["session_settings.html","Session Settings","Session Settings To edit session settings: 1. From the Session menu choose Session Settings . 2. Modify the desired settings on each tab. 3. The d...",""],
["settings_reference.html","Settings Reference","Settings Reference Beyond Compare is highly configurable, and it sometimes can be hard to know where to go in the program to change a specific set...",""],
["setting_program_preferences.html","Program Options","Program Options Tools Options To set program preferences: 1. From the Tools menu, choose Options to open the Options dialog. 2. In the list at the...",""],
["sharing_sessions.html","Sharing Sessions","Sharing Sessions Multiple users can share read-only sessions by using a shared sessions file. From the Tools menu, choose Export Settings to creat...",""],
["snapshot_options.html","Saving Snapshots","Saving Snapshots Tools Save Snapshot To save a snapshot: 1. On the Tools menu, select Save Snapshot . 2. Enter the path of the folder tree to be s...",""],
["source_control_integration.html","Source Control Integration","Source Control Integration Tools Source Control Integration You can associate folders with your SCC-compatible source control application so that ...",""],
["standard_vs_pro.html","Standard vs Pro Editions","Standard vs Pro Editions The Standard edition of Beyond Compare version 3 is a powerful full-featured comparison tool, not a stripped-down \"lite\" ...",""],
["startup_options.html","Startup Options","Startup Options Tools Options Startup Startup options: When Beyond Compare starts up, it normally shows the Home view. To have the program automat...",""],
["support.html","Support, Ordering and License","Support, Ordering and License For the latest version of Beyond Compare and for other news about the program, visit our web site at: www.scootersof...",""],
["synchronize.html","Synchronize","Synchronize Actions Synchronize . . . On the Actions menu, the Synchronize submenu has commands that synchronize the current selection. Update Rig...",""],
["tab_options.html","Tab Options","Tab Options Tools Options Tabs When working with multiple sessions simultaneously, Beyond Compare can open them in independent windows, or under t...",""],
["text_compare.html","Text Compare Overview","Text Compare Overview A Text Compare session visually compares two text files, in a side-by-side or over-under layout. It helps you analyse and re...",""],
["text_compare_alignment.html","Text Compare Alignment Settings","Text Compare Alignment Settings Session Session Settings Alignment The Alignment tab settings control the algorithm for aligning lines in the comp...",""],
["text_compare_commands.html","Text Compare Commands","Text Compare Commands Following is a description of the Text Compare commands, in addition to the common commands . Most of these commands are ava...",""],
["text_compare_formats.html","Text Compare File Formats","Text Compare File Formats Session Session Settings Format Specify the file format to be used when reading the left and/or right files. The default...",""],
["text_compare_importance.html","Text Compare Importance Settings","Text Compare Importance Settings Session Session Settings Importance These settings control which differences you consider important in the curren...",""],
["text_compare_replacements.html","Text Compare Replacements","Text Compare Replacements Session Session Settings Replacements Replacements identify repetitive changes that should be considered unimportant. Yo...",""],
["text_compare_session_settings.html","Text Compare Settings","Text Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs These settings control which files to...",""],
["text_edit.html","Text Edit Overview","Text Edit Overview A Text Edit view is a single-pane text editor. See also Text Edit Commands Text Format Settings Text View Options ",""],
["text_edit_commands.html","Text Edit Commands","Text Edit Commands Following is a description of the Text Edit commands, in addition to the common commands . Most of these commands are available...",""],
["text_format_conversion_settings.html","Text Format Conversion Settings","Text Format Conversion Settings Text Format Conversion The Conversion tab defines how files should be loaded and saved. Text Compare sessions can ...",""],
["text_format_general_settings.html","Text Format General Settings","Text Format General Settings Text Format General The Mask is a set of file types to be associated with this file format. The Description can inclu...",""],
["text_format_grammar_settings.html","Text Format Grammar Settings","Text Format Grammar Settings Text Format Grammar The Grammar tab defines the syntax of a file. Grammar elements such as comments and keywords are ...",""],
["text_format_misc_settings.html","Text Format Miscellaneous Settings","Text Format Miscellaneous Settings Text Format Misc Insert spaces instead of tabs When disabled, pressing the TAB key inserts a tab character into...",""],
["text_merge.html","Text Merge Overview","Text Merge Overview A Text Merge session contains two or three non-editable source panes and an editable output pane. The left and right panes hol...",""],
["text_merge_alignment.html","Text Merge Alignment Settings","Text Merge Alignment Settings Session Session Settings Alignment The Alignment tab settings control the algorithm for aligning lines in the compar...",""],
["text_merge_commands.html","Text Merge Commands","Text Merge Commands Following is a description of the Text Merge commands, in addition to the common commands . Most of these commands are availab...",""],
["text_merge_formats.html","Text Merge File Formats","Text Merge File Formats Session Session Settings Format Specify the file format to be used when reading the input files. The default selection is ...",""],
["text_merge_importance.html","Text Merge Importance Settings","Text Merge Importance Settings Session Session Settings Importance These settings control which differences you consider important in the current ...",""],
["text_merge_session_settings.html","Text Merge Settings","Text Merge Settings Session Session Settings Click the tab containing the settings you want to edit: Specs These settings control which files to m...",""],
["text_patch.html","Text Patch Overview","Text Patch Overview A Text Patch view recreates a comparison represented in a patch file. Patch files can be generated using a Text Compare report...",""],
["text_patch_commands.html","Text Patch Commands","Text Patch Commands Following is a description of the Text Patch commands, in addition to the common commands . Most of these commands are availab...",""],
["text_view_options.html","Text View Options","Text View Options Tools Options File Views Text These options apply to Text Compare and Text Merge sessions. Editing features Auto indent When ena...",""],
["touch.html","Touch","Touch Actions Touch On the Actions menu, the Touch command modifies the timestamp (date/time last modified) of the selected files. If Copy timesta...",""],
["understanding_the_display.html","Understanding the Folder Compare Display","Understanding the Folder Compare Display The Folder Compare display uses color cues to highlight the differences between the two base folders. By ...",""],
["using_beyond_compare.html","Using Beyond Compare","Using Beyond Compare Beyond Compare handles a wide variety of comparison tasks. It has specialized viewers for different kinds of files and differ...",""],
["using_snapshots.html","Using Snapshots","Using Snapshots On the Tools menu, the Save Snapshot command saves a compressed read-only listing of the specified folder and all of its subfolder...",""],
["using_text_merge.html","Using Text Merge","Using Text Merge Once BC has completed the comparison it will show up to four panes: The left, center, and right panes at the top, with an output ...",""],
["version_compare_commands.html","Version Compare Commands","Version Compare Commands Following is a description of the Version Compare commands, in addition to the common commands . Most of these commands a...",""],
["version_compare_session_settings.html","Version Compare Settings","Version Compare Settings Session Session Settings Specs These settings control which files to compare. Importance These settings control which dif...",""],
["walking_through_differences.html","Walking Through Differences","Walking Through Differences The Next Difference Section and Previous Difference Section commands help you step through all the differences in your...",""],
["welcome.html","Welcome","Welcome to Beyond Compare 3 Beyond Compare is a utility for comparing files and folders. It can help you find and reconcile differences in source ...",""],
["whats_new.html","What&#39;s New","What&#39;s New Version 3 is a fairly complete rewrite of Beyond Compare. Like the transition from version 1 to version 2, we took the opportunity to r...",""],
["where_settings_are_stored.html","Where Settings are Stored","Where Settings are Stored on your Computer In a normal installation, Beyond Compare stores your preferences, sessions and customized file formats ...",""]];
